core/urls.py
from django.urls import path

from .views import (
    MainView,
    Categories,
    ModelDetailView,
    PaymentView,
    FreeModelListView,
    download_counter,

    downloads,

    DiscuntView,
    
    PortfolioListView,
    PortfolioDetailView,

    VideosListView,

    AboutUsView,
    Contact,
    save_model,
    go_to_email,
    abcd,

    search_query,
)
from cart.views import (
    CartDetailView,
    add_to_cart_view,
    model_checkbox,
)


app_name='Core'

urlpatterns = [
    path('', MainView.as_view(), name = "main-view"),
    path('category/<int:pk>/', Categories.as_view(), name='category-view'),
    path('model/<slug:slug>/', ModelDetailView.as_view(), name='model-detail-view'),

    path('free/', FreeModelListView.as_view(), name='free-detail-view'),
    path('ajax/download_counter/', download_counter, name='download_counter'),

    path('ajax/downloads/', downloads, name='downloads'),

    path('payment/', PaymentView.as_view(), name='payment-view'),
    path('payment/<int:pk>/', PaymentView.as_view(), name='payment-view'),

    path('portfolio/', PortfolioListView.as_view(), name='portfolio-view'),
    path('portfolio/detail/<slug:slug>/', PortfolioDetailView.as_view(), name='portfolio-detail-view'),

    path('videos/', VideosListView.as_view(), name='video-view'),

    path('card/', CartDetailView.as_view(), name='card-view'),
    path('ajax/cart/detail/', add_to_cart_view, name='add_to_cart_view'),
    path('ajax/model/checkbox/', model_checkbox, name='model_checkbox'),

    path('contact/', Contact.as_view(), name='contact-view'),
    
    path('aksiya/', DiscuntView.as_view(), name='aksiya-view'),

    
    path('about/', AboutUsView.as_view(), name='about-view'),

    path('ajax/search_query/', search_query, name='search_query'),

    path('save_model/', save_model, name='save_model'),

    path('go_to_email/', go_to_email, name='go_to_email'),
    path('abcd/', abcd)
]

download/urls.py
from django.urls import path
from . import views

app_name='download'

urlpatterns = [
    path('card_verify_code', views.card_verify_code, name="card_verify_code"),
    path('<int:pk>/3d-model/zip/', views.make_models_zip, name='zip'),
    path('<int:pk>/<int:os_pk>/3d-model/zip/', views.make_models_zip, name='zip'),
    path('<token>', views.tokenize_address)
]

model_3d/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.conf import settings

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('tinymce/', include('tinymce.urls')),
    path('accounts/', include('django.contrib.auth.urls')),

    # path('', include('core.urls', namespace='Core')),
]

urlpatterns += i18n_patterns(
    # local apps
    path('', include('core.urls', namespace='Core')),
    path('Home/', include('product.urls', namespace='Product')),
    path('accounts/', include('users.urls', namespace='User')),
    path('api/payme/', include('paymeuz.urls')),
    path('download/', include('download.urls', namespace='download')),
)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

static_root/core/urls.py
from django.urls import path

from .views import (
    MainView,
    Categories,
    ModelDetailView,
    PaymentView,
    FreeModelListView,
    download_counter,

    downloads,

    DiscuntView,
    
    PortfolioListView,
    PortfolioDetailView,

    VideosListView,

    AboutUsView,
    Contact,
    save_model, # new

    search_query,
)
from cart.views import (
    CartDetailView,
    add_to_cart_view,
    model_checkbox,
)


app_name='Core'

urlpatterns = [
    path('', MainView.as_view(), name = "main-view"),
    path('category/<int:pk>/', Categories.as_view(), name='category-view'),
    path('model/<slug:slug>/', ModelDetailView.as_view(), name='model-detail-view'),

    path('free/', FreeModelListView.as_view(), name='free-detail-view'),
    path('ajax/download_counter/', download_counter, name='download_counter'),

    path('ajax/downloads/', downloads, name='downloads'),

    path('payment/', PaymentView.as_view(), name='payment-view'),
    path('payment/<int:pk>/', PaymentView.as_view(), name='payment-view'),

    path('portfolio/', PortfolioListView.as_view(), name='portfolio-view'),
    path('portfolio/detail/<slug:slug>/', PortfolioDetailView.as_view(), name='portfolio-detail-view'),

    path('videos/', VideosListView.as_view(), name='video-view'),

    path('card/', CartDetailView.as_view(), name='card-view'),
    path('ajax/cart/detail/', add_to_cart_view, name='add_to_cart_view'),
    path('ajax/model/checkbox/', model_checkbox, name='model_checkbox'),

    path('contact/', Contact.as_view(), name='contact-view'),
    
    path('aksiya/', DiscuntView.as_view(), name='aksiya-view'),

    
    path('about/', AboutUsView.as_view(), name='about-view'),

    path('ajax/search_query/', search_query, name='search_query'),

    path('save_model/', save_model, name='save_model'), # new
]

static_root/users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_view

from .views import NewUserCreationForm, LoginFormView # Contact, Message
from .forms import UserLoginForm

app_name = 'User'

urlpatterns = [
    path('register/', NewUserCreationForm.as_view(), name='register'),
    # path('login/', auth_view.LoginView.as_view(template_name="registration/login.html", authentication_form=UserLoginForm), name='login'),
    path('login/', LoginFormView.as_view(), name='login'),

    # reset password viewes' urls
    path('password-change/', 
        auth_view.PasswordChangeView.as_view(template_name='registration/password_change_form.html'), 
        name='password_change'),
    path('password_change_done/', 
        auth_view.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), 
        name='password_change_done'),
    path('reset_password/', 
        auth_view.PasswordResetView.as_view(template_name='registration/password_reset_form.html'), 
        name='password_reset'),
    path('reset_password_sent/', 
        auth_view.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), 
        name='password_reset_done'),
    path('reset/<uidb64>/<token>/', 
        auth_view.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'), 
        name='password_reset_confirm'),
    path('reset_password_complete/', 
        auth_view.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), 
        name='password_reset_complete'),



    # path('contact/', Contact.as_view(), name='contact'),
    # path('message/', Message.as_view(), name='message'),
]

static_root/product/forms.py
from django import forms

class ModelSearchForm(forms.Form):
	search_query = forms.CharField(
		max_length=300, widget=forms.TextInput(attrs={"placeholder":"Search..."})
	)

static_root/cart/views.py
from django.core.paginator import Paginator
from django.db.models import F
from django.core.mail import send_mail
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, Http404, JsonResponse, BadHeaderError
from django.core import serializers
from django.views import View
from django.core.serializers.json import DjangoJSONEncoder
from django.contrib.auth.mixins import LoginRequiredMixin
from django.template import defaultfilters
from django.conf import settings
from django.db.models import F
from django.core.mail import send_mail
from django.contrib import messages
from django.conf import settings
from datetime import datetime
from django.db.models import Case, Value, When
from django.db.models import Q
import json
import os


from product.models import (
	Category, 
	Product,
)
from .models import *
# Create your views here.


def add_to_cart_view(request):
	data = json.loads(request.body)
	pk = data['pk']
	action = data['action']
	pageid = data['pageid']
	
	print('Action:', action)
	print('Product:', pk)
	print('PageId:', pageid)
	if request.user.is_authenticated:
		customer = request.user.customer
		# print(customer)
		product = Product.objects.get(pk=pk)
		order, created = Order.objects.get_or_create(customer=customer, complete=False)

		orderItem, created = OrderItem.objects.get_or_create(order=order, model=product)
		done_action = {"added":False, "one_more":False, "already_added":False}

		if action == 'add' and pageid == "product-page" and created == True:
			orderItem.quantity = (orderItem.quantity + 1)
			done_action["added"] = True
	# 	# messages.success(request, f"messages now working")
	
		elif action == 'add' and pageid == "product-page" and created == False:
			done_action["already_added"] = True
	# 	messages.success(request, f"messages now working")

	# elif action == 'add' and pageId == "cart-page" and created == False and product.quantity > orderItem.quantity:
	# 	orderItem.quantity = (orderItem.quantity + 1) 
	# 	done_action["one_more"] = True

	# elif action == 'remove':
	# 	orderItem.quantity = (orderItem.quantity - 1)
	
	orderItem.save()

	if action == 'clear':
		orderItem.delete()
	
	# if orderItem.quantity <= 0:
	# 	orderItem.delete()

	return JsonResponse(done_action, safe=False, status=200)
	# return JsonResponse("done_action", safe=False, status=200)


class CartDetailView(View):
	template_name = 'shopingCard.html'
	context       = {}
	total_price = 0
	def get(self, request, *args, **kwargs):
		previous_path = self.request.GET.get('next', '')

		if request.user.is_authenticated:
			customer = self.request.user.customer
			order, created = Order.objects.get_or_create(customer=customer, complete=False)
			print("Order: ", order, '\n', "Created: ", created)
			items = order.orderitem_set.all()

			json_serializer = serializers.get_serializer("json")()
			items_json      = json_serializer.serialize(items, ensure_ascii=False)
		else:
			items = []
			items_json = dict({})
		if len(items) > 0:
			for item in items:
				if item.cart_field and item.model.discount:
					self.total_price += item.model.discount
				elif item.cart_field:
					self.total_price += item.model.price
		self.context = {
			"items":items,
			# "order":order,
			"total_price": self.total_price,
			"previous_path": previous_path,
			"items_json": items_json
		}
		return render(
			request,
			self.template_name,
			self.context,
		)



from django.core.serializers.json import DjangoJSONEncoder
from decimal import Decimal
class LazyEncoder(DjangoJSONEncoder):
	def default(self, obj):
		if isinstance(obj, Decimal):
			return str(obj)
		return super().default(obj)

def model_checkbox(request, *args, **kwargs):
	pk = request.GET.get('pk')
	action = request.GET.get('action')
	print("PrimaryKey: ", type(pk))
	if request.user.is_authenticated:
		customer = request.user.customer
		order, created = Order.objects.get_or_create(customer=customer, complete=False)
		print("Order: ", order, '\n', "Created: ", created)
		items = order.orderitem_set.all()

		print(items)
		print(pk)
		print(action)

		if not created and len(items) > 0:
			if pk == 'all' and action=='checked':
				for item in items:
					item.cart_field = True
					print("PK: ", pk, "Value: ", item.cart_field)
					item.save()
			elif pk == 'all' and action=='unchecked':
				for item in items:
					item.cart_field = False
					print("PK: ", pk, "Value: ", item.cart_field)
					item.save()
			elif pk != '' and action != '':
				for item in items:
					if item.pk == int(pk) and item.cart_field == True:
						item.cart_field = False
						print("PK: ", pk, "Value: ", item.cart_field)
						item.save()
					elif item.pk == int(pk) and item.cart_field == False:
						item.cart_field = True
						print("PK: ", pk, "Value: ", item.cart_field)
						item.save()
	try:
		items_json = serializers.serialize('json', items, cls=LazyEncoder, ensure_ascii=True)
		return JsonResponse({"instance": items_json,}, status=200)
	except Exception as e:
		print("Error occured: ", e)
	return JsonResponse({"instance": "failed",}, status=200)

static_root/download/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from .tasks import zip_maker
import requests
from paymeuz.models import Transaction
from cart.models import *
from .tasks import send_download_page
from cart.models import OrderSingleItem

# @login_required
def create_verify(number, exp_date, amount):
	url = "http://127.0.0.1:8000/api/payme/card/create/"
	data = dict(
		id = id,
		params = dict(
			card = dict(
				number = number,
				expire = exp_date,
			),
			amount = amount,
			save = True
		)
	)
	response = requests.post(url, json = data)
	result = response.json()

	return result


try:
	id = Transaction.objects.all().count() + 1
except:
	pass
amount = 0

# @login_required
def card_verify_code(request):
	if request.method == 'POST':
		url1   = 'http://127.0.0.1:8000/api/payme/card/verify/'
		token  = request.POST['token']
		code   = request.POST['verify_code']
		price  = request.POST['amount']
		modelid = request.POST['blogid']
		print(type(modelid), modelid)

		amount = float(price) * 100
		print("amount: ", type(amount))
		data1 = dict(
			id     = id,
			params = dict(
				token = token,
				code  = code,
			)
		)
		r = requests.post(url1, json=data1)
		result = r.json()

		url2  = 'http://127.0.0.1:8000/api/payme/payment/'
		data2 = dict(
			id     = id,
			params = dict(
				token   = token,
				amount  = amount,
				account = dict(
					order_id = id
				)
			)
		)
		rq = requests.post(url2, json=data2)
		rs = rq.json()
		print(rs)

		try:
			if rs['result']['receipt']['error'] == None:
				print("successfully")
				customer = request.user.customer
				if modelid != 'None':
					send_download_page(request, customer, modelid)
				else:
					send_download_page(request, customer)
			else:
				print("Houston, we have a problem! :(")
		except Exception as e:
			print("Houston, we have a problem! :(\n", e)
		return redirect('/')
	return render(request, "card_verify.html")



from django.http import HttpResponse
try:
	from StringIO import StringIO
except ImportError:
	from io import StringIO, BytesIO
from zipfile import ZipFile
import os
from django.conf import settings
from cart.models import Customer

def make_models_zip(request, pk, os_pk=None, *args, **kwargs):

	# if request.user.is_authenticated:
	# 	customer = request.user.customer
	# 	order, created = Order.objects.get_or_create(customer=customer, complete=False)
	# 	print("Order: ", order, '\n', "Created: ", created)
	# 	items = order.orderitem_set.all()
	model_locations = []
	customer = Customer.objects.get(pk=pk)

	if os_pk:
		order = OrderSingleItem.objects.get(pk=os_pk)
		model_locations.append(order.model.model_file.path)
		return  zip_maker(model_locations, customer)
	else:
		order = Order.objects.get(customer=customer, complete=False)
		items = order.orderitem_set.all()
		
		if len(items) > 0:
			for model in  items:
				if model.cart_field:
					model_locations.append(model.model.model_file.path)
			return  zip_maker(model_locations, customer)
	
	return

static_root/product/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.db.models import F
import json
from django.views.generic import (
    ListView,
    DetailView,
)

from .models import (
    Category,
    Product,
    Images,
) 
# Create your views here.


# Download counter
def download_counter(request):
    Product.objects.filter(slug = request.GET.get('request_data')).update(downloaded = F('downloaded')+1)
    return HttpResponse(
        json.dumps('Increased'),
        content_type="application/json"
    )

static_root/users/views.py
from django.urls import  reverse_lazy
from django.views.generic import CreateView
# from django.contrib.auth.forms import UserCreationForm


from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.http import HttpResponse, Http404, HttpResponseRedirect ,BadHeaderError
from django.views import View

# from django.contrib.auth.forms import  AuthenticationForm  # Now we can use 'LoginForm' instead of 'AuthenticationForm'
from django.views.decorators.csrf import csrf_protect
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.views import LoginView
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from .forms import FeedbackForm
from django.core.mail import send_mail
from django.conf import settings
# from shumoff import settings

from .forms import NewUserForm, UserLoginForm
# from core.models  import Category
# Create your views here.


class NewUserCreationForm(SuccessMessageMixin, CreateView):
    template_name = 'registration/register.html'
    form_class = NewUserForm
    success_url = reverse_lazy('login')
    success_message = "New account for %(first_name)s was created successfully"
   
    def get_success_message(self, cleaned_data):
        return self.success_message % dict(
            cleaned_data,
            first_name=self.object.first_name,
        )


class LoginFormView(SuccessMessageMixin, LoginView):
    template_name="registration/login.html"
    authentication_form=UserLoginForm
    # template_name = 'auth/login.html'
    success_url = reverse_lazy('/')
    success_message = "Email %(username)s were successfully logged in."

    def get_success_message(self, cleaned_data):
        return self.success_message % dict(
            cleaned_data,
            username=self.object.username,
        )



def logout(request):
	logout(request)
	messages.info(request, "Logged out successfully!")
	return redirect("Products:product-list")

static_root/templates/Mahsulot.html
{% extends 'base.html' %}
{% load static %}
{% load thumbnail %}

	{% block css %}
		<!-- icons-link -->
		<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
		<!-- style-link -->
		<link rel="stylesheet" href="{% static 'fancbox/jquery.fancybox.min.css' %}">
		<link rel="stylesheet" href="{% static 'css/style.css' %}">
		<link rel="stylesheet" href="{% static 'css/style2.css' %}">
		<link rel="stylesheet" href="{% static 'css/main.css' %}">
	{% endblock css %}

	{% block title %} <title>Mahsulot</title> {% endblock title %}
	
	{% block bodycontent %}

		<section class="content">

			<section class="content">

				<!-- Navbar -->
				{% include 'includes/navbar.html' %}
				<!-- end Navbar -->

			</section>

		</section>

		<section class="section__wrappers">

			<!-- Images Container -->
			<div class="container fancbox">
				<div class="fancbox__top">
					<a href="javascript:;" data-fancybox-trigger="gallery"  data-caption="{{ object.caption|default_if_none:'Active Image' }}">
						{% if object.video_file %}
							<video width='400' controls>
								<source src="{{ object.video_file.url }}" type='video/mp4'>
								Your browser does not support the video tag.
							</video>
						{% elif object.video_link %}
							<object style="height: 390px; width: 640px">
								<param name="movie" value="http://www.youtube.com/v/{{ object.extract_video_id }}?version=3">
								<param name="allowFullScreen" value="true">
								<param name="allowScriptAccess" value="always">
								<embed src="http://www.youtube.com/v/{{ object.extract_video_id }}?version=3" type="application/x-shockwave-flash" allowfullscreen="true" allowScriptAccess="always" width="640" height="390">
							</object>
						{% else %}
							<img class="fancboxss" src ="{{ object.image.url }}" alt = "rasm" />
						{% endif %}
						
					</a>
				</div>

				<div class="fancbox__right">
					{% for img in object.product_images.all %}
						{% if forloop.counter == 1 %}
							{% thumbnail object.image "1500" as bigimg %}
								{% thumbnail object.image "150x150" crop="center" as smallimg %}
									<a href="{{bigimg.url}}" data-fancybox="gallery" data-caption="{{ object.caption|default_if_none:'Active Image' }}">
										<img class="fancboxs" src="{{smallimg.url}}" alt = "rasm">
									</a>
								{% endthumbnail %}
							{% endthumbnail %}
						{% endif %}
						{% thumbnail img.image "1500" as big %}
							{% thumbnail img.image "150x150" crop="center" as small %}
								<a href="{{big.url}}" data-fancybox="gallery" data-caption="{{ img.caption|default_if_none:'Image' }}">
									<img class="fancboxs" src="{{small.url}}" alt = "rasm">
								</a>
							{% endthumbnail %}
						{% endthumbnail %}
					{% empty %}
					{% endfor %}
				</div>
			</div>
			<!-- End Images Container -->
	
			<div class="slide">

				<!-- Object Info -->
				<div class="slide__about">
					<h2 class="slide__title">{{ object.name }}<br>
						<span class="slide__star slide__letter">
							
							{% if object.discount and object.paid %}
								<small style="color: #aaaaaa"><del>{{ object.price }} so'm</del></small> {{ object.discount }} so'm
							{% elif object.price  and object.paid %}
								{{ object.price }} so'm
							{% else %}
								Bepul
							{% endif %}
								
						</span>
					</h2>

					<h4 class="slide__texts">{{ object.short_info }}</h4>
					<div class="description">
						<p class="slide__text__last">{{ object.description|safe }}</p> 
					</div>
					
				</div>
				<!-- End Object Info -->

				<div class="slide__btn">
					{% if object.paid %}
						<button type="submit" class="slide__buy">
							<a href="{% url 'Core:payment-view' object.pk %}" >Sotib olish</a>
						</button>
						
						<!-- <form action="{% url 'Core:payment-view' %}" method="get">
							{% csrf_token %}
							<button type="submit" onclick="send_amount('{{ object.price }}')" class="slide__buy">Sotib olish</button>
						</form> -->
						<button onclick="add_to_cart_view(this)" data-pk="{{ object.pk }}" data-action="add" data-pageid="product-page" type="submit" class="slide__bug add-to-basket popup">Savatchaga olish
							<span class="popuptext" id="PopupNotification{{object.pk}}">
								<a href="{% url 'login' %}?next={{request.path}}" class="text-white">Login</a> / <a href="{% url 'User:register' %}?next={{request.path}}">Sign Up</a>
							</span>
							<a href="{% url 'Core:card-view' %}?next={{request.path}}" class="popuptext" id="AlreadyAdded{{object.pk}}">Added To Cart</a>
						</button>
					{% else %}
						<a href="{{ object.model_file.url }}" >
							{% csrf_token %}
							<button class="slide__buy"  onclick="download_counter(this)" id="{{ object.slug }}">Yuklab olish</button>
						</a>
					{% endif %}
					
				</div>
			</div>
		</section>

		<!-- Script that calls download_counter method -->
		<script>
			function download_counter($this){
				console.log("button clicked");
				var request_data = $this.id;
				console.log("data: " + request_data);
				$.ajax({
					type: 'GET',
					url: "{% url 'Core:download_counter' %}",
					data : { 
						request_data: request_data,
					},
					success : function(json) {
						$("#request-access").hide();
						console.log("requested access complete");
					}
				});
			}
		</script>
		<!-- End Script -->


	{% endblock bodycontent %}

	{% block js %} 
		<!--jQuery-->
		<script src="{% static 'jQuery/jquery.min.js' %}"></script>
		<script src="{% static 'fancbox/jquery.fancybox.min.js' %}"></script>

		<script>
			function getCookie(name) {
				var cookieValue = null;
				if (document.cookie && document.cookie != '') {
					var cookies = document.cookie.split(';');
					for (var i = 0; i < cookies.length; i++) {
						var cookie = jQuery.trim(cookies[i]);
						// Does this cookie string begin with the name we want?
						if (cookie.substring(0, name.length + 1) == (name + '=')) {
							cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
							break;
						}
					}
				}
				return cookieValue;
			}
			var csrftoken = getCookie('csrftoken');
			function csrfSafeMethod(method) {
				// these HTTP methods do not require CSRF protection
				return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
			}
			$.ajaxSetup({
				beforeSend: function(xhr, settings) {
					if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
						xhr.setRequestHeader("X-CSRFToken", csrftoken);
					}
				}
			});
			function send_amount(amount){			
				//$.ajax({
				//	type: 'GET',
				///	url: "{% url 'Core:payment-view' %}",
				//	csrftoken: csrftoken,
				//	data : {
				//		amount: amount
				//	},
				//	success : function(json) {
				//		console.log("amount sended successfully to payment-view");
				
						$.ajax({
							type: 'GET',
							url: "{% url 'Core:save_model' %}",
							csrftoken: csrftoken,
							data : {
								model_quantity: 1,
								single_price: amount,
								total_price: 0
							},
							success : function(json) {
								console.log("amount sended successfully to card_verify_code");
							}
						});
					}
				//});
				
			//}
		</script>

		<!--/jQuery-->
		<!-- <script src="js/main.js"></script> -->
		<!--/javascript-->

		<!--    bundle js swiper-->
		<script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>
		<script src="{% static 'js/bundle.js' %}"></script>
		<script src="{% static 'js/main.js' %}"></script>
	{% endblock js %} 

static_root/templates/card_verify.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="{% url 'download:card_verify_code' %}" method="POST">
        {% csrf_token %}
        <label for="verify">Tasdiqlash kodi</label>
        <input type="number" name="verify_code" id="verify"/>
        <input type="hidden" name="token" value="{{token}}">
        <input type="hidden" name="amount" value="{{amount}}">
        <input type="hidden" name="blogid" value="{{blogid}}">

        <input type="submit" value="OK">
    </form>
</body>
</html>

static_root/templates/kategorya.html
{% extends 'base.html' %}
{% load static %}

	{% block css %}
		<!-- icons-link -->
		<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"
			integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
		<link rel="stylesheet" href="{% static 'jQuery/lips/owlcarousel2/assets/owl.carousel.min.css' %}">
		<link rel="stylesheet" href="{% static 'jQuery/lips/owlcarousel2/assets/owl.theme.default.min.css' %}">

		<link rel="stylesheet" href="{% static 'css/swiper.min.css' %}">
		<!-- style-link -->
		<link rel="stylesheet" href="{% static 'css/style.css' %}">
		<link rel="stylesheet" href="{% static 'css/main.css' %}">
	{% endblock css %}

	{% block title %} <title>3D model</title> {% endblock title %}
	
	{% block bodycontent %}

		<section class="content">

			<!-- Navbar -->
			{% include 'includes/navbar-free.html' %}
			<!-- end Navbar -->

		</section>

		<section class="freeproducts">
			<div class="freeproducts__title freeproducts--item">
				<div class="freeproducts__line1"></div>
				<div class="freeproducts__text">Mahsulotlar bo'limi</div>
				<div class="freeproducts__line2"></div>
				
			</div>
			
			<div class="freeproducts__cards">
				{% for object in object_list %}
					<div class="freeproducts__card">
						<a href="{% url 'Core:model-detail-view' object.slug %}" >
							<div class="freeproducts__card--title">{{ object.name }}</div>
							<div class="freeproducts__card--image">
								<img src="{{ object.imageURL }}" alt="free product image" class="freeproducts__card--img"></img>
							</div>
							<div class="freeproducts__card--footer">
								<div class="freeproducts__card--current">
									<img src="{% static 'img/icons/sale-current.svg' %}" alt="current img">
									<p> {{ object.downloaded }}</p>
								</div>
								<div class="freeproducts__card--info">Ko’proq malumot</div>
								<img src="{% static 'img/icons/shoppingcardfree.svg' %}" alt="shopping-cart">
							</div>
						</a>
					</div>
				{% endfor %}
			</div>
		</section>


		<!-- Pagination -->
		{% include "includes/paginator.html" %}
		<!-- Pagination -->
	{% endblock bodycontent %}

	{% block js %} 
		<!--jQuery-->
		<script src="{% static 'jQuery/jquery.min.js' %}"></script>
		<script src="{% static 'jQuery/lips/owlcarousel2/owl.carousel.min.js' %}"></script>
		<script src="{% static 'jQuery/jQuery.js' %}"></script>

		<script src="{% static 'js/swiper.min.js' %}"></script>
		<!--/jQuery-->
		<!--javascript-->
		<script src="{% static 'js/main.js' %}"></script>
		<!--/javascript-->
	{% endblock js %}