core/urls.py
from django.urls import path

from .views import (
    MainView,
    Categories,
    ModelDetailView,
    PaymentView,
    FreeModelListView,
    download_counter,

    downloads,

    DiscuntView,
    
    PortfolioListView,
    PortfolioDetailView,

    VideosListView,

    AboutUsView,
    Contact,
    save_model,
    go_to_email,
    abcd,

    search_query,
)
from cart.views import (
    CartDetailView,
    add_to_cart_view,
    model_checkbox,
)


app_name='Core'

urlpatterns = [
    path('', MainView.as_view(), name = "main-view"),
    path('category/<int:pk>/', Categories.as_view(), name='category-view'),
    path('model/<slug:slug>/', ModelDetailView.as_view(), name='model-detail-view'),

    path('free/', FreeModelListView.as_view(), name='free-detail-view'),
    path('ajax/download_counter/', download_counter, name='download_counter'),

    path('ajax/downloads/', downloads, name='downloads'),

    path('payment/', PaymentView.as_view(), name='payment-view'),
    path('payment/<int:pk>/', PaymentView.as_view(), name='payment-view'),

    path('portfolio/', PortfolioListView.as_view(), name='portfolio-view'),
    path('portfolio/detail/<slug:slug>/', PortfolioDetailView.as_view(), name='portfolio-detail-view'),

    path('videos/', VideosListView.as_view(), name='video-view'),

    path('card/', CartDetailView.as_view(), name='card-view'),
    path('ajax/cart/detail/', add_to_cart_view, name='add_to_cart_view'),
    path('ajax/model/checkbox/', model_checkbox, name='model_checkbox'),

    path('contact/', Contact.as_view(), name='contact-view'),
    
    path('aksiya/', DiscuntView.as_view(), name='aksiya-view'),

    
    path('about/', AboutUsView.as_view(), name='about-view'),

    path('ajax/search_query/', search_query, name='search_query'),

    path('save_model/', save_model, name='save_model'),

    path('go_to_email/', go_to_email, name='go_to_email'),
    path('abcd/', abcd)
]

model_3d/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.conf import settings

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('tinymce/', include('tinymce.urls')),
    path('accounts/', include('django.contrib.auth.urls')),

    # path('', include('core.urls', namespace='Core')),
]

urlpatterns += i18n_patterns(
    # local apps
    path('', include('core.urls', namespace='Core')),
    path('Home/', include('product.urls', namespace='Product')),
    path('accounts/', include('users.urls', namespace='User')),
    path('api/payme/', include('paymeuz.urls')),
    path('download/', include('download.urls', namespace='download')),
)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

static_root/core/urls.py
from django.urls import path

from .views import (
    MainView,
    Categories,
    ModelDetailView,
    PaymentView,
    FreeModelListView,
    download_counter,

    downloads,

    DiscuntView,
    
    PortfolioListView,
    PortfolioDetailView,

    VideosListView,

    AboutUsView,
    Contact,
    save_model, # new

    search_query,
)
from cart.views import (
    CartDetailView,
    add_to_cart_view,
    model_checkbox,
)


app_name='Core'

urlpatterns = [
    path('', MainView.as_view(), name = "main-view"),
    path('category/<int:pk>/', Categories.as_view(), name='category-view'),
    path('model/<slug:slug>/', ModelDetailView.as_view(), name='model-detail-view'),

    path('free/', FreeModelListView.as_view(), name='free-detail-view'),
    path('ajax/download_counter/', download_counter, name='download_counter'),

    path('ajax/downloads/', downloads, name='downloads'),

    path('payment/', PaymentView.as_view(), name='payment-view'),
    path('payment/<int:pk>/', PaymentView.as_view(), name='payment-view'),

    path('portfolio/', PortfolioListView.as_view(), name='portfolio-view'),
    path('portfolio/detail/<slug:slug>/', PortfolioDetailView.as_view(), name='portfolio-detail-view'),

    path('videos/', VideosListView.as_view(), name='video-view'),

    path('card/', CartDetailView.as_view(), name='card-view'),
    path('ajax/cart/detail/', add_to_cart_view, name='add_to_cart_view'),
    path('ajax/model/checkbox/', model_checkbox, name='model_checkbox'),

    path('contact/', Contact.as_view(), name='contact-view'),
    
    path('aksiya/', DiscuntView.as_view(), name='aksiya-view'),

    
    path('about/', AboutUsView.as_view(), name='about-view'),

    path('ajax/search_query/', search_query, name='search_query'),

    path('save_model/', save_model, name='save_model'), # new
]

static_root/users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_view

from .views import NewUserCreationForm, LoginFormView # Contact, Message
from .forms import UserLoginForm

app_name = 'User'

urlpatterns = [
    path('register/', NewUserCreationForm.as_view(), name='register'),
    # path('login/', auth_view.LoginView.as_view(template_name="registration/login.html", authentication_form=UserLoginForm), name='login'),
    path('login/', LoginFormView.as_view(), name='login'),

    # reset password viewes' urls
    path('password-change/', 
        auth_view.PasswordChangeView.as_view(template_name='registration/password_change_form.html'), 
        name='password_change'),
    path('password_change_done/', 
        auth_view.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), 
        name='password_change_done'),
    path('reset_password/', 
        auth_view.PasswordResetView.as_view(template_name='registration/password_reset_form.html'), 
        name='password_reset'),
    path('reset_password_sent/', 
        auth_view.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), 
        name='password_reset_done'),
    path('reset/<uidb64>/<token>/', 
        auth_view.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'), 
        name='password_reset_confirm'),
    path('reset_password_complete/', 
        auth_view.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), 
        name='password_reset_complete'),



    # path('contact/', Contact.as_view(), name='contact'),
    # path('message/', Message.as_view(), name='message'),
]

static_root/download/models.py
from django.db import models

# Create your models here.

static_root/core/forms.py
from django import forms

class SearchForm(forms.Form):
	search_query = forms.CharField(
		max_length=300, widget=forms.TextInput(
			attrs={
			"type":"text",
			"id":"search_input_field",
			"name":"search", 
			"placeholder":"Qidirish"}, 
		),
		required=True
	)

static_root/product/forms.py
from django import forms

class ModelSearchForm(forms.Form):
	search_query = forms.CharField(
		max_length=300, widget=forms.TextInput(attrs={"placeholder":"Search..."})
	)

static_root/cart/views.py
from django.core.paginator import Paginator
from django.db.models import F
from django.core.mail import send_mail
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, Http404, JsonResponse, BadHeaderError
from django.core import serializers
from django.views import View
from django.core.serializers.json import DjangoJSONEncoder
from django.contrib.auth.mixins import LoginRequiredMixin
from django.template import defaultfilters
from django.conf import settings
from django.db.models import F
from django.core.mail import send_mail
from django.contrib import messages
from django.conf import settings
from datetime import datetime
from django.db.models import Case, Value, When
from django.db.models import Q
import json
import os


from product.models import (
	Category, 
	Product,
)
from .models import *
# Create your views here.


def add_to_cart_view(request):
	data = json.loads(request.body)
	pk = data['pk']
	action = data['action']
	pageid = data['pageid']
	
	print('Action:', action)
	print('Product:', pk)
	print('PageId:', pageid)
	if request.user.is_authenticated:
		customer = request.user.customer
		# print(customer)
		product = Product.objects.get(pk=pk)
		order, created = Order.objects.get_or_create(customer=customer, complete=False)

		orderItem, created = OrderItem.objects.get_or_create(order=order, model=product)
		done_action = {"added":False, "one_more":False, "already_added":False}

		if action == 'add' and pageid == "product-page" and created == True:
			orderItem.quantity = (orderItem.quantity + 1)
			done_action["added"] = True
	# 	# messages.success(request, f"messages now working")
	
		elif action == 'add' and pageid == "product-page" and created == False:
			done_action["already_added"] = True
	# 	messages.success(request, f"messages now working")

	# elif action == 'add' and pageId == "cart-page" and created == False and product.quantity > orderItem.quantity:
	# 	orderItem.quantity = (orderItem.quantity + 1) 
	# 	done_action["one_more"] = True

	# elif action == 'remove':
	# 	orderItem.quantity = (orderItem.quantity - 1)
	
	orderItem.save()

	if action == 'clear':
		orderItem.delete()
	
	# if orderItem.quantity <= 0:
	# 	orderItem.delete()

	return JsonResponse(done_action, safe=False, status=200)
	# return JsonResponse("done_action", safe=False, status=200)


class CartDetailView(View):
	template_name = 'shopingCard.html'
	context       = {}
	total_price = 0
	def get(self, request, *args, **kwargs):
		previous_path = self.request.GET.get('next', '')

		if request.user.is_authenticated:
			customer = self.request.user.customer
			order, created = Order.objects.get_or_create(customer=customer, complete=False)
			print("Order: ", order, '\n', "Created: ", created)
			items = order.orderitem_set.all()

			json_serializer = serializers.get_serializer("json")()
			items_json      = json_serializer.serialize(items, ensure_ascii=False)
		else:
			items = []
			items_json = dict({})
		if len(items) > 0:
			for item in items:
				if item.cart_field and item.model.discount:
					self.total_price += item.model.discount
				elif item.cart_field:
					self.total_price += item.model.price
		self.context = {
			"items":items,
			# "order":order,
			"total_price": self.total_price,
			"previous_path": previous_path,
			"items_json": items_json
		}
		return render(
			request,
			self.template_name,
			self.context,
		)



from django.core.serializers.json import DjangoJSONEncoder
from decimal import Decimal
class LazyEncoder(DjangoJSONEncoder):
	def default(self, obj):
		if isinstance(obj, Decimal):
			return str(obj)
		return super().default(obj)

def model_checkbox(request, *args, **kwargs):
	pk = request.GET.get('pk')
	action = request.GET.get('action')
	print("PrimaryKey: ", type(pk))
	if request.user.is_authenticated:
		customer = request.user.customer
		order, created = Order.objects.get_or_create(customer=customer, complete=False)
		print("Order: ", order, '\n', "Created: ", created)
		items = order.orderitem_set.all()

		print(items)
		print(pk)
		print(action)

		if not created and len(items) > 0:
			if pk == 'all' and action=='checked':
				for item in items:
					item.cart_field = True
					print("PK: ", pk, "Value: ", item.cart_field)
					item.save()
			elif pk == 'all' and action=='unchecked':
				for item in items:
					item.cart_field = False
					print("PK: ", pk, "Value: ", item.cart_field)
					item.save()
			elif pk != '' and action != '':
				for item in items:
					if item.pk == int(pk) and item.cart_field == True:
						item.cart_field = False
						print("PK: ", pk, "Value: ", item.cart_field)
						item.save()
					elif item.pk == int(pk) and item.cart_field == False:
						item.cart_field = True
						print("PK: ", pk, "Value: ", item.cart_field)
						item.save()
	try:
		items_json = serializers.serialize('json', items, cls=LazyEncoder, ensure_ascii=True)
		return JsonResponse({"instance": items_json,}, status=200)
	except Exception as e:
		print("Error occured: ", e)
	return JsonResponse({"instance": "failed",}, status=200)

static_root/download/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from .tasks import zip_maker
import requests
from paymeuz.models import Transaction
from cart.models import *
from .tasks import send_download_page
from cart.models import OrderSingleItem

# @login_required
def create_verify(number, exp_date, amount):
	url = "http://127.0.0.1:8000/api/payme/card/create/"
	data = dict(
		id = id,
		params = dict(
			card = dict(
				number = number,
				expire = exp_date,
			),
			amount = amount,
			save = True
		)
	)
	response = requests.post(url, json = data)
	result = response.json()

	return result


try:
	id = Transaction.objects.all().count() + 1
except:
	pass
amount = 0

# @login_required
def card_verify_code(request):
	if request.method == 'POST':
		url1   = 'http://127.0.0.1:8000/api/payme/card/verify/'
		token  = request.POST['token']
		code   = request.POST['verify_code']
		price  = request.POST['amount']
		modelid = request.POST['blogid']
		print(type(modelid), modelid)

		amount = float(price) * 100
		print("amount: ", type(amount))
		data1 = dict(
			id     = id,
			params = dict(
				token = token,
				code  = code,
			)
		)
		r = requests.post(url1, json=data1)
		result = r.json()

		url2  = 'http://127.0.0.1:8000/api/payme/payment/'
		data2 = dict(
			id     = id,
			params = dict(
				token   = token,
				amount  = amount,
				account = dict(
					order_id = id
				)
			)
		)
		rq = requests.post(url2, json=data2)
		rs = rq.json()
		print(rs)

		try:
			if rs['result']['receipt']['error'] == None:
				print("successfully")
				customer = request.user.customer
				if modelid != 'None':
					send_download_page(request, customer, modelid)
				else:
					send_download_page(request, customer)
			else:
				print("Houston, we have a problem! :(")
		except Exception as e:
			print("Houston, we have a problem! :(\n", e)
		return redirect('/')
	return render(request, "card_verify.html")



from django.http import HttpResponse
try:
	from StringIO import StringIO
except ImportError:
	from io import StringIO, BytesIO
from zipfile import ZipFile
import os
from django.conf import settings
from cart.models import Customer

def make_models_zip(request, pk, os_pk=None, *args, **kwargs):

	# if request.user.is_authenticated:
	# 	customer = request.user.customer
	# 	order, created = Order.objects.get_or_create(customer=customer, complete=False)
	# 	print("Order: ", order, '\n', "Created: ", created)
	# 	items = order.orderitem_set.all()
	model_locations = []
	customer = Customer.objects.get(pk=pk)

	if os_pk:
		order = OrderSingleItem.objects.get(pk=os_pk)
		model_locations.append(order.model.model_file.path)
		return  zip_maker(model_locations, customer)
	else:
		order = Order.objects.get(customer=customer, complete=False)
		items = order.orderitem_set.all()
		
		if len(items) > 0:
			for model in  items:
				if model.cart_field:
					model_locations.append(model.model.model_file.path)
			return  zip_maker(model_locations, customer)
	
	return

static_root/product/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.db.models import F
import json
from django.views.generic import (
    ListView,
    DetailView,
)

from .models import (
    Category,
    Product,
    Images,
) 
# Create your views here.


# Download counter
def download_counter(request):
    Product.objects.filter(slug = request.GET.get('request_data')).update(downloaded = F('downloaded')+1)
    return HttpResponse(
        json.dumps('Increased'),
        content_type="application/json"
    )

static_root/users/views.py
from django.urls import  reverse_lazy
from django.views.generic import CreateView
# from django.contrib.auth.forms import UserCreationForm


from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.http import HttpResponse, Http404, HttpResponseRedirect ,BadHeaderError
from django.views import View

# from django.contrib.auth.forms import  AuthenticationForm  # Now we can use 'LoginForm' instead of 'AuthenticationForm'
from django.views.decorators.csrf import csrf_protect
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.views import LoginView
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from .forms import FeedbackForm
from django.core.mail import send_mail
from django.conf import settings
# from shumoff import settings

from .forms import NewUserForm, UserLoginForm
# from core.models  import Category
# Create your views here.


class NewUserCreationForm(SuccessMessageMixin, CreateView):
    template_name = 'registration/register.html'
    form_class = NewUserForm
    success_url = reverse_lazy('login')
    success_message = "New account for %(first_name)s was created successfully"
   
    def get_success_message(self, cleaned_data):
        return self.success_message % dict(
            cleaned_data,
            first_name=self.object.first_name,
        )


class LoginFormView(SuccessMessageMixin, LoginView):
    template_name="registration/login.html"
    authentication_form=UserLoginForm
    # template_name = 'auth/login.html'
    success_url = reverse_lazy('/')
    success_message = "Email %(username)s were successfully logged in."

    def get_success_message(self, cleaned_data):
        return self.success_message % dict(
            cleaned_data,
            username=self.object.username,
        )



def logout(request):
	logout(request)
	messages.info(request, "Logged out successfully!")
	return redirect("Products:product-list")

static_root/templates/includes/footer.html
{% load static %}

<footer class="footer">
    <div class="footer__body">
        <div class="footer__info footer__info--end">
            <div class="footer__info--title footer__about--the">Biz haqimizda</div>
            <div class="footer__about">	
                <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Repudiandae, molestiae est placeat asperiores laudantium nobis numquam ipsa eius optio saepe totam sed sequi voluptatum quos architecto nostrum quaerat maiores consequuntur? Maiores quo consectetur soluta vero, nobis magnam est dolor illum quidem dolore ratione illo aperiam veniam provident ipsa officiis! Laborum!</p>
            </div>
        </div>
        <div class="footer__info">
            <a href="index.html" class="footer__info--logo"><img src="{% static 'img/logoii.png' %}" alt="footer logo"></a>
            <div class="footer__info--title">Aloqa Ma'lumotlari</div>
            <a href="tel:+99899 403-68-28" class="footer__info--subtitle">+99899 403-68-28</a>
            <a href="tel:+99899 403-68-28" class="footer__info--subtitle">+99833 888-02-03</a>
            <div class="footer__info--subtitle">khamidullaev@gmail.com</div>
            <div class="footer__info--messangers footer__iconss">
                <a href="#" class="footer__icon--item"><i class="fa fa-instagram"></i></a>
                <a href="#" class="footer__icon--item"><i class="fa fa-youtube"></i></a>
                <a href="#" class="footer__icon--item"><i class="fa fa-telegram"></i></a>
                <a href="#" class="footer__icon--item"><i class="fa fa-facebook"></i></a>
            </div>
        </div>
        <div class="footer__map">
            <div class="mapouter">
                <div class="gmap_canvas"><iframe width="700" height="360" id="gmap_canvas"
                        src="https://maps.google.com/maps?q=uzbekistan%2C%20toshkent%2C%20mirzo%20ulugbek&t=&z=13&ie=UTF8&iwloc=&output=embed"
                        frameborder="0" scrolling="no" marginheight="0" marginwidth="0"></iframe><a
                        href="https://2piratebay.org">free movies</a></div>
            </div>
        </div>
    </div>

    <div class="footer__creators">
        {% now 'Y' as current_year %}
        <p>Barcha huquqlar himoyalangan <span> ©️</span>{{ current_year }} 3D-models </p>
        <p>Sayt yaratuvchi - <a class="footer__company" href="#">Instant Company</a></p>
    </div>
</footer>

static_root/templates/includes/header.html
{% load static %}
<header class="header">
    <div class="header__body">
        <a href="{% url 'Core:main-view'  %}" class="header__logo"><img src="{% static 'img/logoii.png' %}" alt="logo"></a>
        <div class="header__messengers">
            <a class="header__email"ef="email:abbos@gmail.com"><img src="{% static 'img/icon\'s/email.svg' %}" alt="email icon"> abbos@gmail.com</a>
            <a href="#"><img src="{% static 'img/icon\'s/instagram.svg' %}" alt="instagram icon"></a>
            <a href="#"><img src="{% static 'img/icon\'s/youtube.svg' %}" alt="youtube icon"></a>
            <a href="#"><img src="{% static 'img/icon\'s/telegram.svg' %}" alt="telegram icon"></a>
            <a href="#"><img src="{% static 'img/icon\'s/facebook.svg' %}" alt="facebook icon"></a>
        </div>
        <div class="header__signin">
            <img src="{% static 'img/icon\'s/bar-chart.svg' %}" alt="bar-chart icon">
            <p class="header__paragraph" id="Download_counted"></p>
            {% if request.user.is_authenticated %}
                <p class="header__registration">Hi {{ request.user.first_name }}</p>
                <a href="{% url 'logout' %}?next={{request.path}}" class="header__registration">logout</a>          
            {% else %}
                <a href="{% url 'User:register' %}" class="header__registration">Ro'yhatdan o'tish</a>
                <a href="{% url 'login' %}?next={{request.path}}" class="header__registration">Login</a>
            {% endif %}
            <a href="#" class="header__order">Buyurtma berish</a>
            <a href="{% url 'Core:card-view' %}"  class="header__shopcard">
                <img src="{% static 'img/icon\'s/Group.svg' %}" alt="shoping card">
            </a>
        </div>
        <div class="header__language">	
            <select name="dropDown">
                <option value="uz">O'zbek (uz)</a></option>
                <option value="ru">Russia (ru)</option>
                <option value="eng">English (eng)</option>
            </select>
        </div>
        <!-- burger -->
        <div class="navbar__burger h">
            <span></span>
            <span></span>
            <span></span>
        </div>
    </div>
</header>

static_root/templates/includes/messages.html
{% if messages %}
<ul>
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    {% endfor %}
</ul>
{% endif %}

static_root/templates/includes/navbar-free.html
<div class="content__navbar">
    <ul class="content__navbar--list free">
        <li><a href="{% url 'Core:main-view' %}">Asosiy</a></li>
        <li><a href="{% url 'Core:aksiya-view' %}">Aksiya</a></li>
        <li><a href="{% url 'Core:free-detail-view' %}">Bepul mahsulotlar</a></li>
        <li><a href="{% url 'Core:portfolio-view' %}">Portfolio</a></li>
        <li><a href="{% url 'Core:video-view' %}">Videolar</a></li>
        <li><a href="{% url 'Core:about-view' %}">Biz haqimizda</a></li>
        <li><a href="{% url 'Core:contact-view' %}">Aloqa</a></li>
    </ul>
</div>

<!-- 
    free.html
    kategorya.html
    portfolio.html
    shopingCard.html
-->

static_root/templates/includes/navbar.html
<div class="content__navbar">
    <ul class="content__navbar--list">
        <li><a href="{% url 'Core:main-view' %}">Asosiy</a></li>
        <li><a href="{% url 'Core:aksiya-view' %}">Aksiya</a></li>
        <li><a href="{% url 'Core:free-detail-view' %}">Bepul mahsulotlar</a></li>
        <li><a href="{% url 'Core:portfolio-view' %}">Portfolio</a></li>
        <li><a href="{% url 'Core:video-view' %}">Videolar</a></li>
        <li><a href="{% url 'Core:about-view' %}">Biz haqimizda</a></li>
        <li><a href="{% url 'Core:contact-view' %}">Aloqa</a></li>
    </ul>
</div>



static_root/templates/includes/paginator.html
{% load static %}

    {% if is_paginated %}
        
        <div class="blog__counter">
            <div class="blog__counter--number">{{ page_obj.number }} / <span>{{ page_obj.paginator.num_pages }}</span></div>
        </div>
        <div class="blog__btns">
            {% if page_obj.has_previous %}
                <!-- <a href="?page=1">&laquo; 1</a> -->
                <a href="?page={{ page_obj.previous_page_number }}" class="blog__btns--back"> 
                    <img src="{% static 'img/icons/arrow-back.svg' %}" alt="back icon">Back
                </a>
            {% else %}
            <a style="pointer-events: none;" href="" class="blog__btns--back"> 
                <img src="{% static 'img/icons/arrow-back.svg' %}" alt="back icon">Back
            </a>
            {% endif %}
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}" class="blog__btns--next">Next 
                    <img src="{% static 'img/icons/next-icon.svg' %}" alt="next icon">
                </a>
                <!-- <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }} &raquo;</a> -->
            {% else %}
                <a style="pointer-events: none;" href="" class="blog__btns--next">Next 
                    <img src="{% static 'img/icons/next-icon.svg' %}" alt="next icon">
                </a>
            {% endif %}
        </div>

    {% endif %}

    {% if product_object_list %}
    
        <section>
            <div class="blog__counter">
                {% for page_index in page_indexes %}
                    <div class="blog__counter--number"> <span> <a href="?page= {{ page_index }}" style="color:dimgray">{{ page_index }}</a> </span> </div>
                {% endfor %} 
            </div>
            <div class="blog__btns">
                {% if product_object_list.has_previous %}
                    <a href="?page={{ product_object_list.previous_page_number }}" class="blog__btns--back"> <img src="{% static 'img/icons/arrow-back.svg' %}" alt="back icon">Back</a>
                {% else %}
                    <a style="pointer-events: none;" href="" class="blog__btns--back"> <img src="{% static 'img/icons/arrow-back.svg' %}" alt="back icon">Back</a>
                {% endif %}

                {% if product_object_list.has_next %}
                    <a href="?page={{ product_object_list.next_page_number }}" class="blog__btns--next">Next <img src="{% static 'img/icons/next-icon.svg' %}" alt="next icon"></a>
                {% else %}
                    <a style="pointer-events: none;" class="blog__btns--next">Next <img src="{% static 'img/icons/next-icon.svg' %}" alt="next icon"></a>
                {% endif %}
            </div>
        </section>

    {% endif %}>