core/urls.py
from django.urls import path

from .views import (
    MainView,
    Categories,
    ModelDetailView,
    PaymentView,
    FreeModelListView,
    download_counter,

    downloads,

    DiscuntView,
    
    PortfolioListView,
    PortfolioDetailView,

    VideosListView,

    AboutUsView,
    Contact,
    save_model,
    go_to_email,
    abcd,

    search_query,
)
from cart.views import (
    CartDetailView,
    add_to_cart_view,
    model_checkbox,
)


app_name='Core'

urlpatterns = [
    path('', MainView.as_view(), name = "main-view"),
    path('category/<int:pk>/', Categories.as_view(), name='category-view'),
    path('model/<slug:slug>/', ModelDetailView.as_view(), name='model-detail-view'),

    path('free/', FreeModelListView.as_view(), name='free-detail-view'),
    path('ajax/download_counter/', download_counter, name='download_counter'),

    path('ajax/downloads/', downloads, name='downloads'),

    path('payment/', PaymentView.as_view(), name='payment-view'),
    path('payment/<int:pk>/', PaymentView.as_view(), name='payment-view'),

    path('portfolio/', PortfolioListView.as_view(), name='portfolio-view'),
    path('portfolio/detail/<slug:slug>/', PortfolioDetailView.as_view(), name='portfolio-detail-view'),

    path('videos/', VideosListView.as_view(), name='video-view'),

    path('card/', CartDetailView.as_view(), name='card-view'),
    path('ajax/cart/detail/', add_to_cart_view, name='add_to_cart_view'),
    path('ajax/model/checkbox/', model_checkbox, name='model_checkbox'),

    path('contact/', Contact.as_view(), name='contact-view'),
    
    path('aksiya/', DiscuntView.as_view(), name='aksiya-view'),

    
    path('about/', AboutUsView.as_view(), name='about-view'),

    path('ajax/search_query/', search_query, name='search_query'),

    path('save_model/', save_model, name='save_model'),

    path('go_to_email/', go_to_email, name='go_to_email'),
    path('abcd/', abcd)
]

download/urls.py
from django.urls import path
from . import views

app_name='download'

urlpatterns = [
    path('card_verify_code', views.card_verify_code, name="card_verify_code"),
    path('<int:pk>/3d-model/zip/', views.make_models_zip, name='zip'),
    path('<int:pk>/<int:os_pk>/3d-model/zip/', views.make_models_zip, name='zip'),
    path('<token>', views.tokenize_address)
]

model_3d/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.conf import settings

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('tinymce/', include('tinymce.urls')),
    path('accounts/', include('django.contrib.auth.urls')),

    # path('', include('core.urls', namespace='Core')),
]

urlpatterns += i18n_patterns(
    # local apps
    path('', include('core.urls', namespace='Core')),
    path('Home/', include('product.urls', namespace='Product')),
    path('accounts/', include('users.urls', namespace='User')),
    path('api/payme/', include('paymeuz.urls')),
    path('download/', include('download.urls', namespace='download')),
)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

static_root/model_3d/urls.py
from django.conf.urls.static import static
from django.conf import settings

from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    
    # local apps
    path('', include('core.urls', namespace='Core')),
    path('Home/', include('product.urls', namespace='Product')),
    path('accounts/', include('users.urls', namespace='User')),
    path('api/payme/',include('paymeuz.urls')),
    path('download/', include('download.urls',  namespace='download')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_view

from .views import NewUserCreationForm, LoginFormView # Contact, Message
from .forms import UserLoginForm

app_name = 'User'

urlpatterns = [
    path('register/', NewUserCreationForm.as_view(), name='register'),
    # path('login/', auth_view.LoginView.as_view(template_name="registration/login.html", authentication_form=UserLoginForm), name='login'),
    path('login/', LoginFormView.as_view(), name='login'),

    # reset password viewes' urls
    path('password-change/', 
        auth_view.PasswordChangeView.as_view(template_name='registration/password_change_form.html'), 
        name='password_change'),
    path('password_change_done/', 
        auth_view.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), 
        name='password_change_done'),
    path('reset_password/', 
        auth_view.PasswordResetView.as_view(template_name='registration/password_reset_form.html'), 
        name='password_reset'),
    path('reset_password_sent/', 
        auth_view.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), 
        name='password_reset_done'),
    path('reset/<uidb64>/<token>/', 
        auth_view.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'), 
        name='password_reset_confirm'),
    path('reset_password_complete/', 
        auth_view.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), 
        name='password_reset_complete'),



    # path('contact/', Contact.as_view(), name='contact'),
    # path('message/', Message.as_view(), name='message'),
]

templates/Mahsulot.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}
{% load thumbnail %}

	{% block css %}
		<!-- icons-link -->
		<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
		<!-- style-link -->
		<link rel="stylesheet" href="{% static 'fancbox/jquery.fancybox.min.css' %}">
		<link rel="stylesheet" href="{% static 'css/style.css' %}">
		<link rel="stylesheet" href="{% static 'css/style2.css' %}">
		<link rel="stylesheet" href="{% static 'css/main.css' %}">
	{% endblock css %}

	{% block title %} <title>{% trans 'Mahsulot' %}</title> {% endblock title %}
	
	{% block bodycontent %}
		{% get_current_language as LANGUAGE_CODE %}
		<input type='hidden' id='language_type' value="{{ LANGUAGE_CODE }}">

		<section class="content">

			<section class="content">

				<!-- Navbar -->
				{% include 'includes/navbar.html' %}
				<!-- end Navbar -->

			</section>

		</section>

		<section class="section__wrappers">

			<!-- Images Container -->
			<div class="container fancbox">
				<div class="fancbox__top">
					<a href="javascript:;" data-fancybox-trigger="gallery"  data-caption="{{ object.caption|default_if_none:'Active Image' }}">
						{% if object.video_file %}
							<video width='400' controls>
								<source src="{{ object.video_file.url }}" type='video/mp4'>
								{% trans "Brauzeringiz video yorlig'ini qo'llab-quvvatlamaydi." %}
							</video>
						{% elif object.video_link %}
							<object style="height: 390px; width: 640px">
								<param name="movie" value="http://www.youtube.com/v/{{ object.extract_video_id }}?version=3">
								<param name="allowFullScreen" value="true">
								<param name="allowScriptAccess" value="always">
								<embed src="http://www.youtube.com/v/{{ object.extract_video_id }}?version=3" type="application/x-shockwave-flash" allowfullscreen="true" allowScriptAccess="always" width="640" height="390">
							</object>
						{% else %}
							<img class="fancboxss" src ="{{ object.image.url }}" alt = "rasm" />
						{% endif %}
						
					</a>
				</div>

				<div class="fancbox__right">
					{% for img in object.product_images.all %}
						{% if forloop.counter == 1 %}
							{% thumbnail object.image "1500" as bigimg %}
								{% thumbnail object.image "150x150" crop="center" as smallimg %}
									<a href="{{bigimg.url}}" data-fancybox="gallery" data-caption="{{ object.caption|default_if_none:'Active Image' }}">
										<img class="fancboxs" src="{{smallimg.url}}" alt = "rasm">
									</a>
								{% endthumbnail %}
							{% endthumbnail %}
						{% endif %}
						{% thumbnail img.image "1500" as big %}
							{% thumbnail img.image "150x150" crop="center" as small %}
								<a href="{{big.url}}" data-fancybox="gallery" data-caption="{{ img.caption|default_if_none:'Image' }}">
									<img class="fancboxs" src="{{small.url}}" alt = "rasm">
								</a>
							{% endthumbnail %}
						{% endthumbnail %}
					{% empty %}
					{% endfor %}
				</div>
			</div>
			<!-- End Images Container -->
	
			<div class="slide">

				<!-- Object Info -->
				<div class="slide__about">
					<h2 class="slide__title">{{ object.name }}<br>
						<span class="slide__star slide__letter" style="margin-left: 0;">
							
							{% if object.discount and object.paid %}
								<small style="color: #aaaaaa"><del>{{ object.price }} so'm</del></small> {{ object.discount }} {% trans "so'm" %}
							{% elif object.price  and object.paid %}
								{{ object.price }} {% trans "so'm" %}
							{% else %}
								{% trans 'Bepul' %}
							{% endif %}
								
						</span>
					</h2>

					<h4 class="slide__texts">{{ object.short_info }}</h4>
					<div class="description" >
						<p class="slide__text__last" style="max-width: 50px;">{{ object.description|safe }}</p> 
					</div>
					
				</div>
				<!-- End Object Info -->

				<div class="slide__btn" style="margin-top: 15px;">
					{% if object.paid %}
						<button type="submit" class="slide__buy">
							<a href="{% url 'Core:payment-view' object.pk %}" >{% trans "Sotib olish" %}</a>
						</button>
						
						<!-- <form action="{% url 'Core:payment-view' %}" method="get">
							{% csrf_token %}
							<button type="submit" onclick="send_amount('{{ object.price }}')" class="slide__buy">Sotib olish</button>
						</form> -->
						<button onclick="add_to_cart_view(this)" data-pk="{{ object.pk }}" data-action="add" data-pageid="product-page" type="submit" class="slide__bug add-to-basket popup">{% trans 'Savatchaga olish' %}
							<span class="popuptext" id="PopupNotification{{object.pk}}">
								<a href="{% url 'login' %}?next={{request.path}}" class="text-white">{% trans 'Kirish' %}</a> / <a href="{% url 'User:register' %}?next={{request.path}}">{% trans "Ro'yhatdan o'tish" %}</a>
							</span>
							<a href="{% url 'Core:card-view' %}?next={{request.path}}" class="popuptext" id="AlreadyAdded{{object.pk}}">{% trans 'Savatchaga olindi' %}</a>
						</button>
					{% else %}
						<a href="{{ object.model_file.url }}" >
							{% csrf_token %}
							<button class="slide__buy"  onclick="download_counter(this)" id="{{ object.slug }}">{% trans 'Yuklab olish' %}</button>
						</a>
					{% endif %}
					
				</div>
			</div>
		</section>

		<!-- Script that calls download_counter method -->
		<script>
			function download_counter($this){
				console.log("button clicked");
				var request_data = $this.id;
				console.log("data: " + request_data);
				$.ajax({
					type: 'GET',
					url: "{% url 'Core:download_counter' %}",
					data : { 
						request_data: request_data,
					},
					success : function(json) {
						$("#request-access").hide();
						console.log("requested access complete");
					}
				});
			}
		</script>
		<!-- End Script -->


	{% endblock bodycontent %}

	{% block js %} 
		<!--jQuery-->
		<script src="{% static 'jQuery/jquery.min.js' %}"></script>
		<script src="{% static 'fancbox/jquery.fancybox.min.js' %}"></script>

		<script>
			function getCookie(name) {
				var cookieValue = null;
				if (document.cookie && document.cookie != '') {
					var cookies = document.cookie.split(';');
					for (var i = 0; i < cookies.length; i++) {
						var cookie = jQuery.trim(cookies[i]);
						// Does this cookie string begin with the name we want?
						if (cookie.substring(0, name.length + 1) == (name + '=')) {
							cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
							break;
						}
					}
				}
				return cookieValue;
			}
			var csrftoken = getCookie('csrftoken');
			function csrfSafeMethod(method) {
				// these HTTP methods do not require CSRF protection
				return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
			}
			$.ajaxSetup({
				beforeSend: function(xhr, settings) {
					if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
						xhr.setRequestHeader("X-CSRFToken", csrftoken);
					}
				}
			});
			function send_amount(amount){			
				//$.ajax({
				//	type: 'GET',
				///	url: "{% url 'Core:payment-view' %}",
				//	csrftoken: csrftoken,
				//	data : {
				//		amount: amount
				//	},
				//	success : function(json) {
				//		console.log("amount sended successfully to payment-view");
				
						$.ajax({
							type: 'GET',
							url: "{% url 'Core:save_model' %}",
							csrftoken: csrftoken,
							data : {
								model_quantity: 1,
								single_price: amount,
								total_price: 0
							},
							success : function(json) {
								console.log("amount sended successfully to card_verify_code");
							}
						});
					}
				//});
				
			//}
		</script>

		<!--/jQuery-->
		<!-- <script src="js/main.js"></script> -->
		<!--/javascript-->

		<!--    bundle js swiper-->
		<script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>
		<script src="{% static 'js/bundle.js' %}"></script>
		<script src="{% static 'js/main.js' %}"></script>
	{% endblock js %} 

templates/Source code.html
{% load i18n %}
<!-- End Search Script -->
		<script>
	
		function search_quer($this){
			event.preventDefault();

			var query = document.getElementById('search_input_field').value
			document.getElementById('search_input_field').value = " "
			var url =  "{% url 'Core:search_query' %}"
			console.log(query)
			if (query.length != 0){
			
				fetch(url, {
					method:'POST',
					headers:{
						'Content-Type':'application/json',
						'Accept': 'application/json',
						'X-CSRFToken':csrftoken,
					}, 
					body:JSON.stringify({'query': query})
				})
				.then((response) => {
				return response.json();
				})
				.then((data) => {
					if (data == "нет продукта"){
						$("#search-result-modal").html("");
						$("#search-result-modal").prepend(
							`
								<div class="modal__result">
									<div class="product__name">
										<h3 class="product__name--title">{% trans 'Mahsulot mavjud emas' %}}</h3>
									</div>
								</div>
							`
						)
					} else {
						
						var instance = JSON.parse(data);
						$("#search-result-modal").html("");

						for ( var i = 0; i < instance.length; i++){
							var fields = instance[i]["fields"];
							console.log(instance)
							
							console.log("fields", fields)

							var image = fields["image"]

							var discount = fields["discount"]
							var price = "Free"
							if (fields["paid"] === true){
								if (discount == null){
								price = fields["price"]
								}else{
									price = fields["discount"]
								}
							}else{
								price = "Free"
							}
							
							
							$("#search-result-modal").prepend(
								`
									<div class="modal__result">
										<img src="${fields["imageURL"]||""}" alt="product images" class="modal__result--image"></img>
										<div class="product__name">
											<a href="/model/${fields["slug"]}/">
												<h3 class="product__name--title">${fields["name"]||""}</h3>
												<p class="product__name--subtitle">${fields["short_info"]||""}</p>
											</a>
										</div>
										<strong class="product__price">${price}</strong>
									</div>
								`
							)
						}
					}
				});
			} else {
				$("#search-result-modal").html("");
				$("#search-result-modal").prepend(
					`
						<div class="modal__result">
							<div class="product__name">
								<h3 class="product__name--title">{% trans 'Mahsulot mavjud emas' %}</h3>
							</div>
						</div>
					`
				)
			}
		}
  
		

	</script>
	<!-- End Search Script -->

	
	<!-- Modal window -->
	<div class="modal--bg"></div>
	<div class="modal">
		<div class="modal__title">
			<p>Search result </p>
			<p id="closeBtn2"><i class="fa fa-times" id="closeBtn"></i></p>
		</div>
		<div class="modal__main" id = "search-result-modal">
			<div class="modal__result">
				<img src="../static/img/img-1.jpg" alt="product images" class="modal__result--image"></img>
				<div class="product__name">
					<h3 class="product__name--title">{% trans 'Product name..' %}</h3>
					<p class="product__name--subtitle">{% trans "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione veritatis enim maiores repellendus obcaecati provident." %}</p>
				</div>
				<strong class="product__price">$20</strong>
			</div>
		</div>
	</div>
		
	<style>
		
.modal__result {
	display: flex;
	justify-content: space-between;
	align-items: start;
	padding: 20px 7px 20px 0;
  border-bottom: 1px solid #444;
}  
.modal__result--image {
	width: 140px;
	height: 100px;
	object-fit: cover;
	object-position: center;    
	margin: 0px 4px 0px 0px;
}
.product__name {
	width: 40%;
}
.product__name--subtitle {
	color: #444;   
	margin: 10px 0px 0px 0px;
}  
.product__price {
	font-size: 18px;
	
}  
.sliderArrow {
	font-size: 34px;
	color: #444;
	font-weight: bold;
	transition: color ease-in .3s;
	padding: 5px;
}
.sliderArrow:hover {
	color: #000;
}
	</style>
<!--/ Modal window -->

templates/card_verify.html
{% extends "registration/base.html" %}
{% load i18n %}
{% load static %}

	{% block css %}
	<!-- icons-link -->
		<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"
			integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
		<!-- style-link -->
		<link rel="stylesheet" href="{% static 'css/style2.css' %}">
		<!-- style-link -->
		<link rel="stylesheet" href="{% static 'css/style.css' %}">
		<link rel="stylesheet" href="{% static 'css/main.css' %}">
	{% endblock css %}

	{% block title %}
	  <title>{% trans "To'lovni tasdiqlash" %}</title>
	{% endblock title %}

	{% block bodycontent %}

  {% get_current_language as LANGUAGE_CODE %}
  <input type='hidden' id='language_type' value="{{ LANGUAGE_CODE }}">

		<section class="content">

			<!-- Navbar -->
			{% include 'includes/navbar.html' %}
			<!-- end Navbar -->

		</section>
        <div class="verify">
            <div class="payForm__body-2">
                <h2>{% trans "Tasdiqlash kodini kiriting" %}</h2>
                <form action="{% url 'download:card_verify_code' %}" method="POST">
                    {% csrf_token %}
                    <label for="verify">{% trans "Tasdiqlash kodi" %}</label>
                    <input type="number" name="verify_code" id="verify"/><br>
                    <input type="hidden" name="token" value="{{token}}">
                    <input type="hidden" name="amount" value="{{amount}}">
                    <input type="hidden" name="blogid" value="{{blogid}}">

                    <input type="submit" class="payForm__btn" value="OK">
                </form>
            </div>
            <div id="counter"></div>
        </div>
		<style>
            .verify {
                display: flex;
                flex-wrap: wrap;
            }
            #counter {
                display: flex;
                align-items: center;
                /* width: 50%; */
            }
            .base-timer {
              position: relative;
              width: 105px;
            }

            .base-timer__svg {
              transform: scaleX(-1);
            }

            .base-timer__circle {
              fill: none;
              stroke: none;
            }

            .base-timer__path-elapsed {
              stroke-width: 7px;
              stroke: grey;
            }

            .base-timer__path-remaining {
              stroke-width: 7px;
              stroke-linecap: round;
              transform: rotate(90deg);
              transform-origin: center;
              transition: 1s linear all;
              fill-rule: nonzero;
              stroke: currentColor;
            }

            .base-timer__path-remaining.green {
              color: rgb(65, 184, 131);
            }

            .base-timer__path-remaining.orange {
              color: orange;
            }

            .base-timer__path-remaining.red {
              color: red;
            }

            .base-timer__label {
              position: absolute;
              width: 105px;
              height: 105px;
              top: 0;
              display: flex;
              align-items: center;
              justify-content: center;
              font-size: 32px;
            }
            input {
                padding: 5px 2px 5px 10px;
                font-size: 18px;
                outline: none;
                border: 1px solid silver;
                border-radius: 8px;
                margin: 30px 0;
            }

            .verification {
                display: flex;
                flex-direction: column;
                margin: 50px 0;
            }
            .wrapp {
                margin-top: 30px;
                border: 1px solid #777;
                border-radius: 3px;
                width: 270px;
                box-shadow: 1px 2px 5px rgba(0, 0, 0, 0.251);
            }
            .fa {
                color: #43A049;
                font-size: 20px;
                padding: 8px;
                margin-left: -4px;
                cursor: pointer;
            }

            .payForm__body-2 {
                margin: 40px 160px;
                width: 50%;
                max-width: 1366px;
            }
            @media (max-width: 414px) {
              .payForm__body-2 {
                margin: 40px 60px;
              }
              input {
                margin: 24px 0 0;
              }
              .base-timer {
                margin-left: 55px;
              }
            }
            @media (max-width: 375px) {
              .payForm__body-2 {
                margin: 40px 40px;
              }
              .base-timer {
                margin-left: 38px;
              }
            }

            .footer {
                margin-top: 80px;
            }
            button .btn {
                padding: 13px 35px;

                text-transform: uppercase;
                text-align: center;
                background: #05E600;
                box-shadow: 1px 2px 5px rgba(0, 0, 0, 0.31);
                border-radius: 5px;
                color: #fff;
                font-size: 16px;
                transition: all ease-in .3s;
            }
            .payForm__btn {
				text-transform: uppercase;
				padding: 10px 35px;
				background: #05E600;
				box-shadow: 1px 2px 5px rgba(0, 0, 0, 0.31);
				border-radius: 86px;
				color: #fff;
				font-size: 16px;
				transition: all ease-in .3s;
			}
			.payForm__btn:hover {
				background: #049e01;
			}
        </style>
	{% endblock bodycontent %}

	{% block js %}
		<!--jQuery-->
		<script src="{% static 'jQuery/jquery.min.js' %}"></script>
		<script src="{% static 'jQuery/lips/owlcarousel2/owl.carousel.min.js' %}"></script>
		<script src="{% static 'jQuery/jQuery.js' %}"></script>
        <script>
            const FULL_DASH_ARRAY = 283;
            const WARNING_THRESHOLD = 20;
            const ALERT_THRESHOLD = 10;

            const COLOR_CODES = {
              info: {
                color: "green"
              },
              warning: {
                color: "orange",
                threshold: WARNING_THRESHOLD
              },
              alert: {
                color: "red",
                threshold: ALERT_THRESHOLD
              }
            };

            const TIME_LIMIT = 60;
            let timePassed = 0;
            let timeLeft = TIME_LIMIT;
            let timerInterval = null;
            let remainingPathColor = COLOR_CODES.info.color;

            document.getElementById("counter").innerHTML = `
            <div class="base-timer">
              <svg class="base-timer__svg" viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg">
                <g class="base-timer__circle">
                  <circle class="base-timer__path-elapsed" cx="50" cy="50" r="45"></circle>
                  <path
                    id="base-timer-path-remaining"
                    stroke-dasharray="283"
                    class="base-timer__path-remaining ${remainingPathColor}"
                    d="
                      M 50, 50
                      m -45, 0
                      a 45,45 0 1,0 90,0
                      a 45,45 0 1,0 -90,0
                    "
                  ></path>
                </g>
              </svg>
              <span id="base-timer-label" class="base-timer__label">${formatTime(
                timeLeft
              )}</span>
            </div>
            `;

            startTimer();

            function onTimesUp() {
              /*clearInterval(timerInterval);*/
                window.location.replace("{% url 'Core:payment-view' %}");
            }

            function startTimer() {
              timerInterval = setInterval(() => {
                timePassed = timePassed += 1;
                timeLeft = TIME_LIMIT - timePassed;
                document.getElementById("base-timer-label").innerHTML = formatTime(
                  timeLeft
                );
                setCircleDasharray();
                setRemainingPathColor(timeLeft);

                if (timeLeft === 0) {
                  onTimesUp();
                }
              }, 1000);
            }

            function formatTime(time) {
              const minutes = Math.floor(time / 60);
              let seconds = time % 60;

              if (seconds < 10) {
                seconds = `0${seconds}`;
              }

              return `${minutes}:${seconds}`;
            }

            function setRemainingPathColor(timeLeft) {
              const { alert, warning, info } = COLOR_CODES;
              if (timeLeft <= alert.threshold) {
                document
                  .getElementById("base-timer-path-remaining")
                  .classList.remove(warning.color);
                document
                  .getElementById("base-timer-path-remaining")
                  .classList.add(alert.color);
              } else if (timeLeft <= warning.threshold) {
                document
                  .getElementById("base-timer-path-remaining")
                  .classList.remove(info.color);
                document
                  .getElementById("base-timer-path-remaining")
                  .classList.add(warning.color);
              }
            }

            function calculateTimeFraction() {
              const rawTimeFraction = timeLeft / TIME_LIMIT;
              return rawTimeFraction - (1 / TIME_LIMIT) * (1 - rawTimeFraction);
            }

            function setCircleDasharray() {
              const circleDasharray = `${(
                calculateTimeFraction() * FULL_DASH_ARRAY
              ).toFixed(0)} 283`;
              document
                .getElementById("base-timer-path-remaining")
                .setAttribute("stroke-dasharray", circleDasharray);
            }
        </script>


		<!--/jQuery-->
		<!-- <script src="js/bundle.js"></script> -->
		<!--/javascript-->

		<!--    bundle js swiper-->
		<script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>
		<script src="{% static 'js/bundle.js' %}"></script>
        <script src="{% static 'jQuery/jquery.min.js' %}"></script>
		<script src="{% static 'jQuery/lips/owlcarousel2/owl.carousel.min.js' %}"></script>
		<script src="{% static 'jQuery/jQuery.js' %}"></script>

		<script src="{% static 'js/swiper.min.js' %}"></script>
		<!--/jQuery-->
		<script src="{% static 'js/main.js' %}"></script>
		<!--jQuery-->
	{% endblock js %}